### ISSUE TITLE
An error occurred: Failed to execute 'postMessage' on 'Worker': #<Memory> could not be cloned.

### ISSUE THREAD

**Issue by foreinbug** [chemicstry/wasm_thread#24]
environment:
* rustc 1.80.0-nightly (72fdf913c 2024-06-05)
* cargo 1.80.0-nightly (34a6a87d8 2024-06-04)
* wasm-pack 0.12.1
* nightly-x86_64-pc-windows-msvc

No cross domain, use self-signed HTTPS;

cargo.toml
``` toml
[package]
name = "simple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm_thread = { version = "0.3.0", default-features = false }
log = "0.4"
wasm-bindgen = "0.2"
console_log = { version = "1.0", features = ["color"] }
console_error_panic_hook = "0.1"
```

src/lib.rs
``` rust
use std::time::Duration;

use wasm_bindgen::prelude::*;
use wasm_thread as thread;

#[wasm_bindgen(start)]
fn main() {
    console_log::init().unwrap();
    console_error_panic_hook::set_once();

    for _ in 0..2 {
        thread::spawn(|| {
            for i in 1..3 {
                log::info!(
                    "hi number {} from the spawned thread {:?}!",
                    i,
                    thread::current().id()
                );
                thread::sleep(Duration::from_millis(1));
            }
        });
    }

    for i in 1..3 {
        log::info!(
            "hi number {} from the main thread {:?}!",
            i,
            thread::current().id()
        );
    }
}
```

build.ps1
``` powershell
wasm-pack build --dev --out-dir ./module/target --target web --features wasm_thread/es_modules
```

``` javascript
simple.js:338 
 panicked at C:\Users\ASUS\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wasm_thread-0.3.0\src\wasm32\mod.rs:349:10:
called `Result::unwrap()` on an `Err` value: JsValue(DataCloneError: Failed to execute 'postMessage' on 'Worker': #<Memory> could not be cloned.
Error: Failed to execute 'postMessage' on 'Worker': #<Memory> could not be cloned.
```

**Comment by foreinbug** [comment]
> Do you have cross origin isolation header set? It is required for web workers, see #23

yes, I added two response headers

``` javascript
  ctx.set("Cross-Origin-Embedder-Policy", "require-corp");
  ctx.set("Cross-Origin-Opener-Policy", "same-origin");
``` 
and there are no cross-domain issues

**Comment by foreinbug** [comment]
> Do you have cross origin isolation header set? It is required for web workers, see #23

However, there is no cross-domain problem, and the loaded files are all in the same domain

``` javascript
  ctx.set("Cross-Origin-Embedder-Policy", "require-corp");
  ctx.set("Cross-Origin-Opener-Policy", "same-origin");
```
I tried to add these response headers, but the error was the same

**Comment by justinlovinger** [comment]
I have the same issue. `window.crossOriginIsolated` returns true. The site works over `localhost` with the same headers. This error only occurs when deployed and accessed via a non-`localhost` address.

**Comment by justinlovinger** [comment]
With help from `daxpedda` on Discord, I discovered the issue is mostly likely related to compiling without the right flags, not cross-origin isolation. In my case, an issue with my build-script may be the culprit. As they pointed out, the memory that is failing to clone is `ArrayBuffer`, not `SharedArrayBuffer`.

**Comment by AThilenius** [comment]
(Updated)

I'm running into the same issue with `wasm-pack`, though the `wasm-bindgen` based build works. Here is a repro in Docker

```docker filename="Dockerfile"
FROM rust
RUN rustup toolchain install nightly
RUN rustup component add rust-src --toolchain nightly
RUN cargo install wasm-bindgen-cli
RUN cargo install sfz
RUN curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

RUN git clone https://github.com/chemicstry/wasm_thread.git

WORKDIR /wasm_thread
RUN bash build_wasm.sh

WORKDIR /wasm_thread/examples-wasm-pack
RUN wasm-pack build --dev --out-dir ./module/target --target web --features wasm_thread/es_modules
RUN wasm-pack build --dev --out-dir ./no-module/target --target no-modules

WORKDIR /wasm_thread
CMD sfz . -b 0.0.0.0 --coi
```

Run is with
```sh
docker build . --tag wasm_thread_test
docker run --rm -p 5000:5000 wasm_thread_test
```

http://localhost:5000/examples/simple.html works correctly (though with warnings about deprecated initialization parameters) but both of the wasm_pack examples don't work. Same error as OP, and COEP and COOP headers are correctly set.

**Comment by AThilenius** [comment]
Finally figured out my issue, the flags had to be set in `.cargo/config.toml` instead of my env (in my case via a `flake.nix`)

```toml
[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+atomics,+bulk-memory,+mutable-globals"]

[unstable]
build-std = ["std,panic_abort"]
```
